// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_o6po6Ox_DSH1yaYSrCSKaIiEt04HaE',
    appId: '1:661669744477:android:0d8b02ffc963fcf083a2b4',
    messagingSenderId: '661669744477',
    projectId: 'foodiehub-47232',
    storageBucket: 'foodiehub-47232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBibu-IB7gyh0pE8BoCS7iSvmRV5CSH79U',
    appId: '1:661669744477:ios:5ac4ab96c55a5e1383a2b4',
    messagingSenderId: '661669744477',
    projectId: 'foodiehub-47232',
    storageBucket: 'foodiehub-47232.firebasestorage.app',
    androidClientId: '661669744477-35avka6si54dt1fg5rogst77s191op3j.apps.googleusercontent.com',
    iosClientId: '661669744477-opvn2adhv96rc3qap1tv6kulfb074911.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodieHup',
  );
}
